name: CI

on:
  push:
    branches:
      - main
      - dev
      - python-tests
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install C++ Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make libgtest-dev libgmock-dev

    - name: Build Project
      run: make

  run_tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make libgtest-dev libgmock-dev python3 python3-pip
        pip3 install --upgrade pip

    - name: Build C++ Tests
      run: make test

    - name: Run C++ Tests
      run: ./test-ascii85

    - name: Run Python Tests
      run: make test-python
